services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  rabbitmq:
    image: rabbitmq:alpine
    restart: always

  bike:
    build:
      dockerfile: bike/Dockerfile
      context: ./services
    restart: always
    ports:
      - 8081:8080
    environment:
      DB_URL: mongodb://root:example@mongo:27017
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - mongo
      - rabbitmq

  geo:
    build:
      dockerfile: geo/Dockerfile
      context: ./services
    restart: always
    ports:
      - 8082:8080
    environment:
      DB_URL: mongodb://root:example@mongo:27017
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - mongo
      - rabbitmq