name: 'Lint'
description: 'Run linter on specified module'
inputs:
  path:
    required: true
    description: 'Path to the directory to lint'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - uses: actions/checkout@v3  
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        working-directory: ${{ inputs.path }}