name: golangci-lint
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: read
jobs:
  list-services:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.set-services.outputs.service }}
    steps:
      - uses: actions/checkout@v2
      - id: set-services
        run: echo "::set-output name=service::$(ls -d services/* | jq -R -s -c 'split("\n")[:-1]')"

  golangci:
    needs: list-services
    strategy:
        matrix:
            service: ${{ fromJson(needs.list-services.outputs.services) }}
    runs-on: ubuntu-latest
    name: Lint ${{ matrix.service }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3  
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ${{ matrix.service }}

        